### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by ghost** [Iragne/react-native-app-info#1]
Are there any plans to add Android support?

**Comment by Iragne** [comment]
Dell let me Time to go back and yes. Also if you want to create a PR. I will be happy too.

**Comment by sodik82** [comment]
any update or new plans?

**Comment by Iragne** [comment]
PR are welcome

**Comment by Iragne** [comment]
Thank to @sodik82  for the PR

**Comment by sodik82** [comment]
any plans to release it to npm (with new version)?
