### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by eyaleizenberg** [Iragne/react-native-app-info#2]
Trying to run this in React Native 0.11 I get this:

<img width="372" alt="screen shot 2015-09-20 at 17 42 23" src="https://cloud.githubusercontent.com/assets/1061345/9981206/f6ac3a5e-5fbe-11e5-832f-d499762ee7d2.png">

**Comment by traviskochel** [comment]
In case you, or anyone else is still wondering about this, you just have to link the xcode project, and binary. Pull request to update the readme here: https://github.com/Iragne/react-native-app-info/pull/3

**Comment by Iragne** [comment]
Thank @traviskochel
