### ISSUE TITLE
Support for React Native >= 0.40

### ISSUE THREAD

**Issue by oureta** [Iragne/react-native-app-info#6]
On RN v0.40, iOS native headers have been moved. Imports of RN Headers should be changed from:

`#import "RCTUtils.h"`

to

`#import <React/RCTUtils.h>`

**Comment by ohmyguigs** [comment]
+1 take a look at my PR, credits to [this medium post](https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.v7qzfwvmf)
@Iragne @madox2 @traviskochel pls 😁

**Comment by guilhermebruzzi** [comment]
Nice @ohmyguigs

**Comment by oureta** [comment]
@Iragne can you upload a new version reflecting this change on npm? thank you.
